sudo: false
language: php

php:
  - 7.0.7
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
  - composer create-project nette/coding-standard coding-standard
  - mv tests/temp/git tests/temp/.git

script:
  - coding-standard/vendor/symplify/easy-coding-standard/bin/ecs check src/ tests/ --config coding-standard/coding-standard-php70.neon
  - vendor/bin/tester -p php-cgi tests

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
